import { Inter } from "next/font/google";
import { AuthContextProvider } from "@/context/UserContext";
import { Toaster } from "@/components/ui/toaster";
import Navbar from "@/components/Navbar";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/themeprovider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <AuthContextProvider>
          <Navbar />
          <div className="w-screen h-screen flex flex-col justify-end p-5">
            {children}
          </div>
          <Toaster />
        </AuthContextProvider>
      </ThemeProvider>
    </>
  );
}
